# Generated by Django 2.2.7 on 2019-11-11 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='photo',
            field=models.ImageField(default='default.png', null=True, upload_to='profile_image/%Y/%m/%d/'),
        ),
    ]
