# Generated by Django 2.2.7 on 2019-11-12 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=50, null=True)),
                ('slug', models.CharField(max_length=30, null=True)),
                ('value', models.CharField(max_length=250, null=True)),
                ('type', models.CharField(max_length=11, null=True)),
                ('description', models.CharField(max_length=250, null=True)),
            ],
        ),
    ]
